### ISSUE TITLE
is this automation only for lights domain?

### ISSUE THREAD

**Issue by lpt2007** [haberda/light_automation#6]
I try to use light_automation with switch domain but for some reason not working?

here si configuration:
```
daily_mosquito:
  module: light_automation
  class: light_automation
  entity_id:
    - switch.room_daily_socket_ext_01
  on_time: sunset + 01:00:00
  off_time: sunrise - 01:00:00
```

Under AppDeamon - threads i can see last active date, but switch not turning on/off

any idea?
